export const db_M_R = {
    'M': {
        'NAME': ['Mabel', 'Mac', 'Mack', 'Mackenzie', 'Macy', 'Madeline', 'Madelyn', 'Madison', 'Mae', 'Magdalena', 'Maggie', 'Malia', 'Mallory', 'Mamie', 'Mandy', 'Manuel', 'Marc', 'Marcel', 'Marcella', 'Marco', 'Marcus', 'Margaret', 'Margarita', 'Margie', 'Marguerite', 'Mari', 'Maria', 'Marian', 'Marianne', 'Maribel', 'Maricela', 'Marie', 'Marietta', 'Marilyn', 'Marina', 'Mario', 'Marion', 'Marisa', 'Marisol', 'Marissa', 'Marjorie', 'Mark', 'Marla', 'Marlene', 'Marlon', 'Marquita', 'Marshall', 'Martha', 'Martin', 'Martina', 'Marty', 'Marvin', 'Mary', 'Maryann', 'Mason', 'Mathew', 'Matt', 'Matthew', 'Maude', 'Maureen', 'Maurice', 'Max', 'Maxine', 'Maxwell', 'May', 'Maya', 'Megan', 'Meghan', 'Mel', 'Melanie', 'Melba', 'Melinda', 'Melissa', 'Melody', 'Melvin', 'Mercedes', 'Meredith', 'Merle', 'Mia', 'Micah', 'Michael', 'Micheal', 'Michele', 'Michelle', 'Mickey', 'Miguel', 'Mike', 'Mildred', 'Miles', 'Millicent', 'Milo', 'Milton', 'Mindy', 'Minerva', 'Minnie', 'Miranda', 'Miriam', 'Misty', 'Mitch', 'Mitchell', 'Mitzi', 'Moises', 'Mollie', 'Molly', 'Mona', 'Monica', 'Monique', 'Monroe', 'Monte', 'Monty', 'Morgan', 'Morris', 'Moses', 'Muriel', 'Myles', 'Myra', 'Myron', 'Myrtle'],
        'VEGETABLE': ['Maize', 'Malabar Spinach', 'Mallow', 'Mangetout', 'Marrow', 'Mashua', 'Molhe', 'Morel', 'Moringa', 'Mung Bean', 'Mushroom', 'Mustard Greens'],
        'FRUIT': ['Macadamia Nut', 'Malay Apple', 'Mamey Sapote', 'Mammee Apple', 'Mamoncillo', 'Mandarin', 'Mango', 'Mangosteen', 'Manila Tamarind', 'Maprang', 'Maqui Berry', 'Marang', 'Marionberry', 'Marula', 'Mayhaw', 'Melon', 'Melon Pear', 'Meyer Lemon', 'Miracle Fruit', 'Mock Strawberry', 'Monstera Deliciosa', 'Mora de Castilla', 'Morinda', 'Mountain Soursop', 'Mulberry', 'Muscadine', 'Muskmelon'],
        'CITY': ['Macau', 'Madison', 'Madrid', 'Madurai', 'Makassar', 'Malabo', 'Malacca', 'Malaga', 'Male', 'Malmo', 'Managua', 'Manaus', 'Manchester', 'Mandalay', 'Mangalore', 'Manila', 'Maputo', 'Mar del Plata', 'Maracaibo', 'Maracay', 'Marseille', 'Mashhad', 'Mbabane', 'Mecca', 'Medan', 'Medellini', 'Medina', 'Melbourne', 'Memphis', 'Mendoza', 'Merida', 'Mersin', 'Mesa', 'Mexicali', 'Mexico City', 'Miami', 'Milan', 'Milwaukee', 'Minneapolis', 'Minsk', 'Mogadishu', 'Mombasa', 'Monaco', 'Monrovia', 'Monterrey', 'Montevideo', 'Montreal', 'Moscow', 'Mosul', 'Multan', 'Mumbai', 'Munich', 'Murmansk', 'Muscat', 'Mykolaiv', 'Mysore'],
        'JOB': ['Machine Operator', 'Machinist', 'Magician', 'Magistrate', 'Maid', 'Mail Carrier', 'Maintenance Worker', 'Make-Up Artist', 'Makeup Artist', 'Management Consultant', 'Manager', 'Manicurist', 'Manufacturer', 'Marine Biologist', 'Market Researcher', 'Market Trader', 'Marketing Manager', 'Mason', 'Massage Therapist', 'Mathematician', 'Mayor', 'Mechanic', 'Mediator', 'Medical Assistant', 'Medical Student', 'Merchant', 'Messenger', 'Metal Worker', 'Meteorologist', 'Microbiologist', 'Midwife', 'Military Officer', 'Miller', 'Milliner', 'Millwright', 'Miner', 'Minister', 'Missionary', 'Mobile Developer', 'Model', 'Moderator', 'Mold Maker', 'Money Broker', 'Mortgage Broker', 'Mortician', 'Mover', 'Musician', 'Musicologist'],
        'ANIMAL': ['Macaque', 'Macaw', 'Mackerel', 'Maggot', 'Magpie', 'Maine Coon', 'Malamute', 'Mallard', 'Mamba', 'Manatee', 'Mandrill', 'Manta Ray', 'Mantis', 'Marmoset', 'Marmot', 'Marsupial', 'Marten', 'Mastiff', 'Mayfly', 'Meadowlark', 'Meerkat', 'Megfalodon', 'Mink', 'Minnow', 'Mite', 'Mockingbird', 'Mole', 'Mollusk', 'Mongoose', 'Monitor Lizard', 'Monkey', 'Monkfish', 'Moose', 'Moray Eel', 'Mosquito', 'Moth', 'Mouse', 'Mule', 'Mullet', 'Muskox', 'Muskrat', 'Mussel', 'Mustang', 'Myna'],
        'INANIMATE': ['Macaroni', 'Machine', 'Machinery', 'Macro', 'Magazine', 'Magic', 'Magician', 'Magnet', 'Magnolia', 'Magnitude', 'Maid', 'Mail', 'Mailbox', 'Main', 'Maize', 'Makeup', 'Male', 'Mall', 'Mallet', 'Mama', 'Mammal', 'Man', 'Management', 'Manager', 'Mandarin', 'Mandolin', 'Mane', 'Mango', 'Manhole', 'Manicure', 'Mannequin', 'Manor', 'Mansion', 'Mantel', 'Mantle', 'Manual', 'Maple', 'Map', 'Marble', 'March', 'Mare', 'Margaret', 'Margarine', 'Margin', 'Mariachi', 'Marimba', 'Mark', 'Market', 'Marker', 'Marmalade', 'Marriage', 'Marrow', 'Mars', 'Marsh', 'Marten', 'Mask', 'Mason', 'Mass', 'Mast', 'Master', 'Mat', 'Match', 'Material', 'Math', 'Mathematics', 'Matrix', 'Matter', 'Mattress', 'Maximum', 'May', 'Mayonnaise', 'Mayor', 'Maze', 'Meal', 'Measure', 'Measurement', 'Meat', 'Mechanic', 'Medal', 'Media', 'Medicine', 'Medium', 'Meet', 'Meeting', 'Melody', 'Melon', 'Member', 'Memo', 'Memorial', 'Memory', 'Men', 'Mentor', 'Menu', 'Merchant', 'Mercury', 'Mercy', 'Merit', 'Mesh', 'Mess', 'Message', 'Metal', 'Meteor', 'Meter', 'Method', 'Metro', 'Microphone', 'Microscope', 'Microwave', 'Midday', 'Middle', 'Midnight', 'Mile', 'Milk', 'Milkshake', 'Mill', 'Millimeter', 'Million', 'Mimic', 'Mind', 'Mine', 'Mineral', 'Minibus', 'Minimum', 'Minister', 'Mink', 'Minnow', 'Minor', 'Mint', 'Minute', 'Mirror', 'Missile', 'Mist', 'Mistake', 'Mitten', 'Mix', 'Mixer', 'Mixture', 'Moat', 'Mobile', 'Mob', 'Moccasin', 'Model', 'Modem', 'Moisture', 'Mole', 'Molecule', 'Mom', 'Moment', 'Money', 'Mongrel', 'Monitor', 'Monkey', 'Monk', 'Month', 'Monument', 'Moon', 'Mop', 'Morning', 'Morse', 'Mosquito', 'Moss', 'Motel', 'Moth', 'Mother', 'Motion', 'Motor', 'Motorboat', 'Motorcycle', 'Motorist', 'Mountain', 'Mouse', 'Mousetrap', 'Mouth', 'Movement', 'Movie', 'Mower', 'Mud', 'Mug', 'Mule', 'Multimedia', 'Muscle', 'Museum', 'Mushroom', 'Music', 'Musical', 'Musician', 'Mustard', 'Mutton', 'Mystery', 'Myth']
    },
    'N': {
        'NAME': ['Nadine', 'Nancy', 'Nanette', 'Nannie', 'Naomi', 'Natalia', 'Natalie', 'Natasha', 'Nathan', 'Nathaniel', 'Neal', 'Ned', 'Neil', 'Nell', 'Nellie', 'Nelson', 'Nettie', 'Neva', 'Nicholas', 'Nichole', 'Nick', 'Nickolas', 'Nicolas', 'Nicole', 'Nigel', 'Nikki', 'Nina', 'Nita', 'Noah', 'Noe', 'Noel', 'Noelle', 'Nola', 'Nolan', 'Nona', 'Nora', 'Norah', 'Norbert', 'Norma', 'Norman', 'Nova'],
        'VEGETABLE': ['Napa Cabbage', 'Navy Bean', 'Nettle', 'New Zealand Spinach'],
        'FRUIT': ['Nageia', 'Nance', 'Naranjilla', 'Nashi Pear', 'Natal Plum', 'Nauseberry', 'Nectarine', 'Neem', 'Nere', 'Nonda Plum', 'Noni', 'Northern Spy Apple', 'Nutmeg'],
        'CITY': ['Nagano', 'Nagasaki', 'Nagoya', 'Nairobi', 'Namangan', 'Nanchang', 'Nanjing', 'Nanning', 'Nantes', 'Naples', 'Nashville', 'Nassau', 'Natal', 'Naypyidaw', 'Ndjamena', 'New Delhi', 'New Haven', 'New Orleans', 'New York', 'Newark', 'Newcastle', 'Niamey', 'Nice', 'Nicosia', 'Nizhny Novgorod', 'Norfolk', 'Norilsk', 'Norman', 'North Las Vegas', 'Norwich', 'Nottingham', 'Nouakchott', 'Novosibirsk', 'Nuremberg'],
        'JOB': ['Nanny', 'Narrator', 'Naturalist', 'Navigator', 'Negotiator', 'Neurologist', 'Neurosurgeon', 'Newsreader', 'Newspaper Editor', 'Night Watchman', 'Novelist', 'Nuclear Engineer', 'Nuclear Scientist', 'Nun', 'Nurse', 'Nursery Worker', 'Nutritionist'],
        'ANIMAL': ['Naked Mole Rat', 'Narwhal', 'Nautilus', 'Needlefish', 'Nematode', 'Newfoundland', 'Newt', 'Nighthawk', 'Nightingale', 'Numbat', 'Nurse Shark', 'Nutcracker', 'Nuthatch', 'Nutria', 'Nyala'],
        'INANIMATE': ['Nail', 'Name', 'Nap', 'Napkin', 'Nation', 'Natural', 'Nature', 'Navy', 'Neck', 'Necklace', 'Necktie', 'Need', 'Needle', 'Negative', 'Neighbor', 'Neighborhood', 'Neon', 'Nephew', 'Nerve', 'Nest', 'Net', 'Network', 'News', 'Newspaper', 'Newsstand', 'Next', 'Nicotine', 'Niece', 'Night', 'Nightgown', 'Nightmare', 'Nine', 'Nitrogen', 'No', 'Nobody', 'Noise', 'Nonsense', 'Noodle', 'Noon', 'North', 'Nose', 'Note', 'Notebook', 'Notepad', 'Nothing', 'Notice', 'Noun', 'Novel', 'November', 'Now', 'Nozzle', 'Number', 'Nurse', 'Nursery', 'Nut', 'Nutmeg', 'Nutrition', 'Nylon']
    },
    'O': {
        'NAME': ['Octavio', 'Odell', 'Odessa', 'Ola', 'Olga', 'Olive', 'Oliver', 'Olivia', 'Ollie', 'Omar', 'Opal', 'Ophelia', 'Ora', 'Oralia', 'Orando', 'Orville', 'Oscar', 'Osvaldo', 'Otis', 'Otto', 'Owen'],
        'VEGETABLE': ['Oca', 'Okra', 'Onion', 'Orach', 'Oregano'],
        'FRUIT': ['Oil Palm', 'Okra', 'Old World Sycamore', 'Olive', 'Ollalieberry', 'Oloyu', 'Orange', 'Oregon Grape', 'Otaheite Gooseberry'],
        'CITY': ['Oakland', 'Oaxaca', 'Odessa', 'Oklahoma City', 'Olomouc', 'Omaha', 'Omsk', 'Oran', 'Oranjestad', 'Orlando', 'Osaka', 'Oshawa', 'Oslo', 'Ostrava', 'Ottawa', 'Ouagadougou', 'Oulu', 'Oviedo', 'Oxford'],
        'JOB': ['Obstetrician', 'Occupational Therapist', 'Oceanographer', 'Oculist', 'Office Manager', 'Office Worker', 'Officer', 'Oil Tycoon', 'Oncologist', 'Opera Singer', 'Operator', 'Ophthalmologist', 'Optician', 'Optometrist', 'Oral Surgeon', 'Orator', 'Orderly', 'Organist', 'Ornamental Horticulturist', 'Ornithologist', 'Orthodontist', 'Orthopedist', 'Osteopath', 'Outfitter'],
        'ANIMAL': ['Ocelot', 'Octopus', 'Okapi', 'Old English Sheepdog', 'Olive Ridley Sea Turtle', 'Olm', 'Opossum', 'Orangutan', 'Orca', 'Oriole', 'Oryx', 'Osprey', 'Ostrich', 'Otter', 'Owl', 'Ox', 'Oyster', 'Oystercatcher'],
        'INANIMATE': ['Oak', 'Oar', 'Oasis', 'Oat', 'Oatmeal', 'Object', 'Objection', 'Objective', 'Oboe', 'Observation', 'Observatory', 'Occasion', 'Occupation', 'Ocean', 'Octagon', 'Octave', 'October', 'Octopus', 'Odd', 'Odometer', 'Offense', 'Offer', 'Office', 'Officer', 'Official', 'Oil', 'Olive', 'Omelet', 'One', 'Onion', 'Open', 'Opera', 'Operation', 'Opinion', 'Opponent', 'Opportunity', 'Opposite', 'Option', 'Orange', 'Orchestra', 'Orchid', 'Order', 'Ore', 'Organ', 'Organization', 'Organism', 'Original', 'Ornament', 'Ostrich', 'Other', 'Ounce', 'Out', 'Outcome', 'Outfit', 'Outlet', 'Outline', 'Output', 'Outside', 'Oval', 'Oven', 'Overcoat', 'Overhead', 'Owl', 'Owner', 'Ox', 'Oxygen', 'Oyster', 'Ozone']
    },
    'P': {
        'NAME': ['Pablo', 'Page', 'Paige', 'Pam', 'Pamela', 'Pansy', 'Parker', 'Pat', 'Patrice', 'Patricia', 'Patrick', 'Patsy', 'Patti', 'Patty', 'Paul', 'Paula', 'Paulette', 'Pauline', 'Pearl', 'Pearlie', 'Pedro', 'Peggy', 'Penelope', 'Penny', 'Percy', 'Perry', 'Pete', 'Peter', 'Petra', 'Philip', 'Phillip', 'Philomena', 'Phoebe', 'Phyllis', 'Pierre', 'Polly', 'Porfirio', 'Preston', 'Prince', 'Priscilla'],
        'VEGETABLE': ['Pak Choi', 'Parsley', 'Parsnip', 'Pattypan Squash', 'Pea', 'Peanut', 'Pearl Onion', 'Pepper', 'Pigeon Pea', 'Pinto Bean', 'Plantain', 'Potato', 'Prairie Turnip', 'Pumpkin', 'Purple Sprouting Broccoli', 'Purslane'],
        'FRUIT': ['Pacific Rose Apple', 'Palestinian Sweet Lime', 'Papaya', 'Parsonage Pear', 'Passion Fruit', 'Pawpaw', 'Peach', 'Peach Palm', 'Peanut', 'Pear', 'Pecan', 'Pequi', 'Persimmon', 'Phalsa', 'Pigeon Pea', 'Pigface', 'Pili Nut', 'Pineapple', 'Pineberry', 'Pink Pearl Apple', 'Pinkel', 'Pinova Apple', 'Pitaya', 'Plantain', 'Plum', 'Plumcot', 'Pomegranate', 'Pomelo', 'Ponderosa Lemon', 'Prickly Pear', 'Prune', 'Pummelo', 'Pumpkin', 'Purple Mangosteen'],
        'CITY': ['Padang', 'Palembang', 'Palermo', 'Palm Springs', 'Palma', 'Palo Alto', 'Panama City', 'Papeete', 'Paramaribo', 'Paris', 'Pasadena', 'Patna', 'Pattaya', 'Pau', 'Pecs', 'Peking', 'Perm', 'Perth', 'Peshawar', 'Philadelphia', 'Phnom Penh', 'Phoenix', 'Phuket', 'Pietermaritzburg', 'Pittsburgh', 'Plovdiv', 'Plymouth', 'Podgorica', 'Pointe-Noire', 'Port Elizabeth', 'Port Harcourt', 'Port Louis', 'Port Moresby', 'Port-au-Prince', 'Port-of-Spain', 'Portland', 'Porto', 'Porto Alegre', 'Portsmouth', 'Potsdam', 'Poznan', 'Prague', 'Praia', 'Pretoria', 'Providence', 'Puebla', 'Pune', 'Pusan', 'Pyongyang'],
        'JOB': ['Packer', 'Painter', 'Paleontologist', 'Paperhanger', 'Paralegal', 'Paramedic', 'Park Ranger', 'Parking Attendant', 'Parole Officer', 'Party Planner', 'Passenger', 'Pastry Chef', 'Pathologist', 'Patrol Officer', 'Pattern Maker', 'Paviour', 'Pawnbroker', 'Pediatrician', 'Pedicurist', 'Pensioner', 'Perfumer', 'Personal Assistant', 'Personal Trainer', 'Pest Controller', 'Pet Groomer', 'Pet Sitter', 'Petroleum Engineer', 'Pharmacist', 'Pharmacologist', 'Philanthropist', 'Phlebotomist', 'Photographer', 'Photojournalist', 'Physiatrist', 'Physical Therapist', 'Physician', 'Physicist', 'Physiologist', 'Physiotherapist', 'Pianist', 'Pilot', 'Pipe Fitter', 'Pizza Delivery Driver', 'Planner', 'Plant Manager', 'Plasterer', 'Plastic Surgeon', 'Playwright', 'Plumber', 'Podiatrist', 'Poet', 'Police Officer', 'Politician', 'Pollster', 'Porter', 'Portfolio Manager', 'Postal Worker', 'Postmaster', 'Potter', 'Poultryman', 'Preacher', 'President', 'Press Operator', 'Principal', 'Printmaker', 'Prison Officer', 'Private Detective', 'Private Investigator', 'Probation Officer', 'Producer', 'Product Manager', 'Professor', 'Programmer', 'Project Manager', 'Projectionist', 'Promoter', 'Proofreader', 'Property Developer', 'Property Manager', 'Prosecutor', 'Prosthetist', 'Psychiatrist', 'Psychologist', 'Public Relations Officer', 'Publican', 'Publisher', 'Purchasing Agent'],
        'ANIMAL': ['Pademelon', 'Panther', 'Parakeet', 'Parrot', 'Partridge', 'Peacock', 'Peafowl', 'Pekingese', 'Pelican', 'Penguin', 'Perch', 'Peregrine Falcon', 'Persian', 'Pheasant', 'Pig', 'Pigeon', 'Pika', 'Pike', 'Piranha', 'Platypus', 'Pointer', 'Polar Bear', 'Pomeranian', 'Pond Skater', 'Poodle', 'Porcupine', 'Porpoise', 'Possum', 'Prawn', 'Praying Mantis', 'Primate', 'Puffin', 'Pug', 'Puma', 'Python'],
        'INANIMATE': ['Pacifier', 'Pack', 'Package', 'Packet', 'Pad', 'Paddle', 'Page', 'Pagoda', 'Pail', 'Pain', 'Paint', 'Paintbrush', 'Painting', 'Pair', 'Pajamas', 'Palace', 'Palm', 'Pamphlet', 'Pan', 'Pancake', 'Panel', 'Panic', 'Pansy', 'Panties', 'Pants', 'Pantyhose', 'Paper', 'Paperback', 'Parade', 'Paragraph', 'Parallel', 'Parcel', 'Parent', 'Park', 'Parking', 'Parrot', 'Parsley', 'Part', 'Particle', 'Partner', 'Party', 'Pass', 'Passage', 'Passenger', 'Passport', 'Password', 'Pasta', 'Paste', 'Pastry', 'Patch', 'Path', 'Patient', 'Patio', 'Patrol', 'Pattern', 'Pause', 'Pavement', 'Paw', 'Pawn', 'Pay', 'Payment', 'Peace', 'Peach', 'Peacock', 'Peak', 'Peanut', 'Pear', 'Pearl', 'Peasant', 'Pebble', 'Pecan', 'Pedal', 'Pedestrian', 'Peel', 'Peg', 'Pen', 'Penalty', 'Pencil', 'Pendulum', 'Penguin', 'Penicillin', 'Penny', 'Pension', 'People', 'Pepper', 'Percentage', 'Perch', 'Perfume', 'Period', 'Periodical', 'Peripheral', 'Permission', 'Person', 'Pest', 'Pet', 'Petal', 'Pharmacist', 'Phase', 'Pheasant', 'Philosophy', 'Phone', 'Photo', 'Photograph', 'Photographer', 'Phrase', 'Physical', 'Physics', 'Piano', 'Pick', 'Pickle', 'Picture', 'Pie', 'Piece', 'Pig', 'Pigeon', 'Pile', 'Pill', 'Pillow', 'Pilot', 'Pimple', 'Pin', 'Pine', 'Pineapple', 'Pink', 'Pint', 'Pipe', 'Pirate', 'Pistol', 'Pit', 'Pitch', 'Pitcher', 'Pizza', 'Place', 'Plain', 'Plan', 'Plane', 'Planet', 'Plant', 'Plantation', 'Plastic', 'Plate', 'Platform', 'Play', 'Playground', 'Playroom', 'Pleasure', 'Plier', 'Plot', 'Plow', 'Plug', 'Plum', 'Plumber', 'Plunger', 'Plywood', 'Pocket', 'Pocketbook', 'Poem', 'Poet', 'Poetry', 'Point', 'Poison', 'Pole', 'Police', 'Policeman', 'Polish', 'Politician', 'Politics', 'Pollen', 'Pond', 'Pony', 'Pool', 'Pop', 'Popcorn', 'Poppy', 'Population', 'Porch', 'Pork', 'Port', 'Porter', 'Portfolio', 'Portion', 'Portrait', 'Position', 'Possibility', 'Post', 'Postage', 'Postbox', 'Poster', 'Pot', 'Potato', 'Potential', 'Pouch', 'Poultry', 'Pound', 'Powder', 'Power', 'Practice', 'Prairie', 'Prawn', 'Prayer', 'Preface', 'Preference', 'Prefix', 'Pregnancy', 'Preparation', 'Presence', 'Present', 'Presentation', 'President', 'Press', 'Pressure', 'Price', 'Pride', 'Priest', 'Primary', 'Prince', 'Princess', 'Print', 'Printer', 'Printing', 'Priority', 'Prison', 'Prisoner', 'Privacy', 'Prize', 'Problem', 'Procedure', 'Process', 'Produce', 'Product', 'Production', 'Profession', 'Professional', 'Professor', 'Profile', 'Profit', 'Program', 'Progress', 'Project', 'Promise', 'Promotion', 'Prompt', 'Pronoun', 'Proof', 'Propaganda', 'Property', 'Proposal', 'Prose', 'Protection', 'Protein', 'Protest', 'Protocol', 'Province', 'Psychology', 'Pub', 'Public', 'Publication', 'Publicity', 'Publishing', 'Puddle', 'Puffin', 'Pull', 'Pulp', 'Pulse', 'Pump', 'Pumpkin', 'Punch', 'Punctuation', 'Punishment', 'Pupil', 'Puppet', 'Puppy', 'Purchase', 'Purple', 'Purpose', 'Purse', 'Push', 'Put', 'Puzzle', 'Pyjama', 'Pyramid']
    },
    'Q': {
        'NAME': ['Quentin', 'Quincy', 'Quinn', 'Quintin', 'Quinton'],
        'VEGETABLE': ['Quandong', 'Quinoa'],
        'FRUIT': ['Quandong', 'Quararibea cordata', 'Queen Anne Cherry', 'Queen Apple', 'Queen Tahiti Pineapples', 'Queensland Nut', 'Querina Apple', 'Quince'],
        'CITY': ['Qingdao', 'Qinhuangdao', 'Qiqihar', 'Qom', 'Quebec City', 'Queenstown', 'Queretaro', 'Quetta', 'Quezon City', 'Quincy', 'Quito'],
        'JOB': ['Quality Assurance Manager', 'Quality Control Inspector', 'Quantity Surveyor', 'Quarry Manager', 'Quartermaster', 'Queen', 'Question Setter', 'Quilt Maker', 'Quizmaster'],
        'ANIMAL': ['Quail', 'Quelea', 'Quetzal', 'Quokka', 'Quoll'],
        'INANIMATE': ['Quad', 'Quadrant', 'Quail', 'Quality', 'Quantity', 'Quart', 'Quarter', 'Quartz', 'Queen', 'Question', 'Quicksand', 'Quiet', 'Quill', 'Quilt', 'Quince', 'Quit', 'Quiz', 'Quote']
    },
    'R': {
        'NAME': ['Rachel', 'Rachael', 'Rafael', 'Ralph', 'Ramiro', 'Ramon', 'Ramona', 'Randal', 'Randall', 'Randolph', 'Randy', 'Raphael', 'Raul', 'Ray', 'Raymond', 'Raymundo', 'Rebecca', 'Rebekah', 'Reed', 'Reggie', 'Regina', 'Reginald', 'Reid', 'Reinaldo', 'Rene', 'Renee', 'Reuben', 'Rex', 'Rey', 'Reyes', 'Reynaldo', 'Rhett', 'Rhonda', 'Ricardo', 'Rich', 'Richard', 'Richie', 'Rick', 'Rickey', 'Rickie', 'Ricky', 'Rico', 'Rigoberto', 'Riley', 'Rita', 'Rob', 'Robbie', 'Robby', 'Robert', 'Roberta', 'Roberto', 'Robin', 'Robyn', 'Rochelle', 'Rocky', 'Rod', 'Roderick', 'Rodger', 'Rodney', 'Rodolfo', 'Rodrigo', 'Rogelio', 'Roger', 'Roland', 'Rolando', 'Roman', 'Romeo', 'Ron', 'Ronald', 'Ronnie', 'Roosevelt', 'Rory', 'Rosa', 'Rosalie', 'Rosalind', 'Rosalinda', 'Rosario', 'Rose', 'Roseann', 'Rosella', 'Rosemarie', 'Rosemary', 'Rosetta', 'Rosie', 'Roslyn', 'Ross', 'Rowena', 'Roxanne', 'Roy', 'Royce', 'Ruben', 'Ruby', 'Rudolph', 'Rudy', 'Rufus', 'Russ', 'Russell', 'Rusty', 'Ruth', 'Ruthie', 'Ryan'],
        'VEGETABLE': ['Radicchio', 'Radish', 'Rampion', 'Rapini', 'Red Cabbage', 'Red Leaf Lettuce', 'Red Onion', 'Red Pepper', 'Rhubarb', 'Rice', 'Ricebean', 'Rocket l', 'Roma Tomato', 'Romaine Lettuce', 'Romanesco Broccoli', 'Rosemary', 'Runner Bean', 'Rutabaga', 'Rye'],
        'FRUIT': ['Rainier Cherry', 'Raisin', 'Rambai', 'Rambutan', 'Ramontchi', 'Rangpur', 'Raspberry', 'Red Banana', 'Red Bayberry', 'Red Currant', 'Red Delicious Apple', 'Red Grape', 'Red Huckleberry', 'Red Mombin', 'Red Mulberry', 'Redcurrant', 'Rhobs el Arsa', 'Riberry', 'Ridged Gourd', 'Rimu', 'Rock Melon', 'Rollinia', 'Rose Apple', 'Rose Hip', 'Roseleaf Bramble', 'Rough Lemon'],
        'CITY': ['Rabat', 'Raleigh', 'Ramallah', 'Ranchi', 'Randburg', 'Rangoon', 'Rapid City', 'Ras Al Khaimah', 'Ravenna', 'Rawalpindi', 'Reading', 'Recife', 'Red Deer', 'Redding', 'Regensburg', 'Regina', 'Reims', 'Reno', 'Rennes', 'Reykjavik', 'Rhodes', 'Richmond', 'Riga', 'Rimini', 'Rio de Janeiro', 'Riyadh', 'Roanoke', 'Rochester', 'Rockford', 'Rome', 'Rosario', 'Rostock', 'Rotorua', 'Rotterdam', 'Rouen', 'Ruse', 'Rustenburg'],
        'JOB': ['Rabbi', 'Race Driver', 'Racehorse Trainer', 'Radiation Therapist', 'Radio DJ', 'Radio Mechanic', 'Radio Operator', 'Radio Producer', 'Radio Presenter', 'Radiographer', 'Radiologist', 'Railroad Engineer', 'Railway Worker', 'Rancher', 'Ranger', 'Real Estate Agent', 'Receptionist', 'Record Producer', 'Recording Artist', 'Recreation Officer', 'Recruitment Consultant', 'Rector', 'Referee', 'Reflexologist', 'Refrigeration Mechanic', 'Refuse Collector', 'Registrar', 'Rehabilitation Counselor', 'Reporter', 'Researcher', 'Reservationist', 'Restaurant Manager', 'Restaurateur', 'Retail Manager', 'Retail Worker', 'Retired', 'Revenue Officer', 'Rheumatologist', 'Ride Operator', 'Rigger', 'Risk Manager', 'Road Sweeper', 'Roadie', 'Robot', 'Robotics Engineer', 'Rocket Scientist', 'Roofer', 'Rope Access Technician', 'Roustabout', 'Rugby Player'],
        'ANIMAL': ['Rabbit', 'Raccoon', 'Racer Snake', 'Ragdoll', 'Rat', 'Rattlesnake', 'Raven', 'Red Fox', 'Red Panda', 'Red Wolf', 'Reindeer', 'Reptile', 'Rhinoceros', 'River Dolphin', 'River Otter', 'Roadrunner', 'Robin', 'Rockfish', 'Rodent', 'Roe Deer', 'Roller', 'Rook', 'Rooster', 'Rottweiler', 'Roundworm', 'Ruff', 'Russell Terrier'],
        'INANIMATE': ['Rabbit', 'Raccoon', 'Race', 'Racing', 'Racket', 'Radar', 'Radiator', 'Radio', 'Radium', 'Radius', 'Rage', 'Raid', 'Rail', 'Railroad', 'Railway', 'Rain', 'Rainbow', 'Raincoat', 'Rainfall', 'Rainstorm', 'Raise', 'Rake', 'Ram', 'Ramp', 'Ranch', 'Range', 'Ranking', 'Raspberry', 'Rat', 'Rate', 'Ratio', 'Raven', 'Ravioli', 'Ray', 'Rayon', 'Razor', 'Reach', 'Reaction', 'Read', 'Reader', 'Reading', 'Reality', 'Rear', 'Reason', 'Receipt', 'Reception', 'Recess', 'Recipe', 'Record', 'Recorder', 'Recording', 'Recovery', 'Rectangle', 'Red', 'Reduction', 'Reef', 'Reel', 'Reference', 'Reflection', 'Refrigerator', 'Refuse', 'Region', 'Register', 'Regret', 'Regulation', 'Reindeer', 'Reject', 'Relation', 'Relationship', 'Relative', 'Relaxation', 'Release', 'Relief', 'Religion', 'Relish', 'Remain', 'Remainder', 'Remark', 'Remedy', 'Reminder', 'Remote', 'Removal', 'Rent', 'Repair', 'Repayment', 'Repeat', 'Replacement', 'Reply', 'Report', 'Representative', 'Republic', 'Request', 'Requirement', 'Research', 'Reserve', 'Reservoir', 'Resident', 'Resignation', 'Resin', 'Resistance', 'Resolution', 'Resort', 'Resource', 'Respect', 'Response', 'Responsibility', 'Rest', 'Restaurant', 'Result', 'Resume', 'Retail', 'Retirement', 'Return', 'Revenue', 'Review', 'Revision', 'Reward', 'Rhinoceros', 'Rhythm', 'Rib', 'Ribbon', 'Rice', 'Rich', 'Ride', 'Ridge', 'Rifle', 'Right', 'Rim', 'Ring', 'Rink', 'Riot', 'Risk', 'Rite', 'River', 'Road', 'Roadway', 'Roast', 'Robe', 'Robin', 'Robot', 'Rock', 'Rocket', 'Rod', 'Role', 'Roll', 'Roller', 'Roof', 'Room', 'Root', 'Rope', 'Rose', 'Rotation', 'Route', 'Router', 'Routine', 'Row', 'Rowboat', 'Royal', 'Rubber', 'Rubbish', 'Ruby', 'Ruffle', 'Rug', 'Rugby', 'Ruin', 'Rule', 'Ruler', 'Rumor', 'Run', 'Runner', 'Running', 'Runway', 'Rush', 'Rust', 'Ruth', 'Rye']
    }
};
