export const db_A_F = {
    'A': {
        'NAME': ['Aaron', 'Abigail', 'Adam', 'Adrian', 'Aidan', 'Alan', 'Albert', 'Alex', 'Alexander', 'Alice', 'Alicia', 'Allison', 'Alyssa', 'Amanda', 'Amber', 'Amelia', 'Amy', 'Andrea', 'Andrew', 'Angela', 'Ann', 'Anna', 'Anthony', 'Antonio', 'Arthur', 'Ashley', 'Audrey', 'Austin', 'Ava', 'Axel', 'Ayden'],
        'VEGETABLE': ['Acorn Squash', 'Alfalfa', 'Amaranth', 'Artichoke', 'Arugula', 'Asparagus', 'Aubergine', 'Avocado'],
        'FRUIT': ['Abiu', 'Acai', 'Acerola', 'Ackee', 'Apple', 'Apricot', 'Avocado'],
        'CITY': ['Aberdeen', 'Abidjan', 'Abu Dhabi', 'Abuja', 'Acapulco', 'Accra', 'Addis Ababa', 'Adelaide', 'Ahmedabad', 'Aleppo', 'Alexandria', 'Algiers', 'Almaty', 'Amman', 'Amsterdam', 'Anaheim', 'Anchorage', 'Ankara', 'Antalya', 'Antwerp', 'Athens', 'Atlanta', 'Auckland', 'Austin'],
        'JOB': ['Accountant', 'Acrobat', 'Actor', 'Actuary', 'Acupuncturist', 'Administrator', 'Admiral', 'Advisor', 'Agent', 'Agronomist', 'Air Traffic Controller', 'Ambassador', 'Analyst', 'Animator', 'Anthropologist', 'Archaeologist', 'Architect', 'Archivist', 'Artist', 'Astronaut', 'Astronomer', 'Athlete', 'Attorney', 'Auctioneer', 'Author'],
        'ANIMAL': ['Aardvark', 'Albatross', 'Alligator', 'Alpaca', 'Anaconda', 'Angelfish', 'Ant', 'Anteater', 'Antelope', 'Ape', 'Aphid', 'Armadillo', 'Asp', 'Ass', 'Auk', 'Avocet', 'Axolotl'],
        'INANIMATE': ['Abacus', 'Accordion', 'Acid', 'Acorn', 'Action figure', 'Adapter', 'Adhesive', 'Aerosol', 'Airplane', 'Alarm', 'Album', 'Alcohol', 'Alloy', 'Alphabet', 'Altar', 'Aluminum', 'Ambulance', 'Amplifier', 'Amulet', 'Anchor', 'Android', 'Antenna', 'Anvil', 'Apartment', 'Apple', 'Apron', 'Aquarium', 'Arch', 'Archive', 'Arena', 'Ark', 'Armor', 'Arrow', 'Art', 'Artifact', 'Ash', 'Asphalt', 'Asteroid', 'Atlas', 'Atom', 'Audio', 'Auger', 'Automobile', 'Axe', 'Axle']
    },
    'B': {
        'NAME': ['Bailey', 'Barbara', 'Barry', 'Beatrice', 'Bella', 'Ben', 'Benjamin', 'Bennett', 'Bernadette', 'Bernard', 'Beth', 'Betty', 'Beverly', 'Bianca', 'Bill', 'Billy', 'Blake', 'Bob', 'Bobby', 'Bonnie', 'Boris', 'Brad', 'Bradley', 'Brandon', 'Brenda', 'Brendan', 'Brent', 'Brett', 'Brian', 'Brianna', 'Bridget', 'Brittany', 'Brooke', 'Bruce', 'Bryan', 'Bryce'],
        'VEGETABLE': ['Bamboo Shoots', 'Basil', 'Bean Sprouts', 'Beans', 'Beetroot', 'Beets', 'Belgian Endive', 'Bell Pepper', 'Bitter Melon', 'Black Beans', 'Bok Choy', 'Broccoli', 'Brussels Sprouts', 'Butternut Squash'],
        'FRUIT': ['Banana', 'Baobab', 'Barberry', 'Bearberry', 'Beechnut', 'Bilberry', 'Bitter Melon', 'Black Cherry', 'Black Raspberry', 'Black Sapote', 'Blackberry', 'Blackcurrant', 'Blood Orange', 'Blueberry', 'Boysenberry', 'Breadfruit', 'Buddhas Hand'],
        'CITY': ['Baghdad', 'Baku', 'Bali', 'Baltimore', 'Bamako', 'Bangalore', 'Bangkok', 'Bangui', 'Barcelona', 'Barranquilla', 'Basra', 'Beijing', 'Beirut', 'Belfast', 'Belgrade', 'Belmopan', 'Belo Horizonte', 'Bengaluru', 'Bergen', 'Berlin', 'Bern', 'Birmingham', 'Bishkek', 'Bogota', 'Boise', 'Bologna', 'Bombay', 'Bonn', 'Bordeaux', 'Boston', 'Brasilia', 'Bratislava', 'Brazzaville', 'Brisbane', 'Bristol', 'Brussels', 'Bucharest', 'Budapest', 'Buenos Aires', 'Buffalo', 'Bujumbura', 'Bulawayo', 'Bursa', 'Busan'],
        'JOB': ['Babysitter', 'Baggage Handler', 'Bailiff', 'Baker', 'Banker', 'Barber', 'Barista', 'Bartender', 'Biologist', 'Blacksmith', 'Blogger', 'Bodyguard', 'Bookkeeper', 'Botanist', 'Brewer', 'Bricklayer', 'Broadcaster', 'Broker', 'Builder', 'Bus Driver', 'Business Analyst', 'Butcher', 'Butler'],
        'ANIMAL': ['Baboon', 'Badger', 'Bald Eagle', 'Bandicoot', 'Barnacle', 'Barracuda', 'Basilisk', 'Bass', 'Bat', 'Bear', 'Beaver', 'Bedbug', 'Bee', 'Beetle', 'Bengal Tiger', 'Bison', 'Blackbird', 'Boa', 'Boar', 'Bobcat', 'Bonobo', 'Booby', 'Buffalo', 'Bug', 'Bulldog', 'Bullfrog', 'Bumblebee', 'Butterfly', 'Buzzard'],
        'INANIMATE': ['Baby', 'Backpack', 'Bacon', 'Badge', 'Bag', 'Bagel', 'Bagpipes', 'Bait', 'Bakery', 'Ball', 'Balloon', 'Bamboo', 'Banana', 'Band', 'Bandana', 'Banjo', 'Bank', 'Banner', 'Bar', 'Barbecue', 'Barcode', 'Barn', 'Barrel', 'Barrier', 'Base', 'Baseball', 'Basin', 'Basket', 'Basketball', 'Bat', 'Bath', 'Bathroom', 'Battery', 'Beacon', 'Bead', 'Beaker', 'Bean', 'Bear', 'Beard', 'Bed', 'Bedroom', 'Bee', 'Beef', 'Beer', 'Beetle', 'Bell', 'Belt', 'Bench', 'Beret', 'Berry', 'Bicycle', 'Bike', 'Bill', 'Bin', 'Binoculars', 'Bird', 'Biscuit', 'Bit', 'Blackboard', 'Blade', 'Blanket', 'Blender', 'Block', 'Blog', 'Blood', 'Blouse', 'Blowtorch', 'Blueberry', 'Board', 'Boat', 'Body', 'Bolt', 'Bomb', 'Bone', 'Book', 'Bookcase', 'Boot', 'Border', 'Bottle', 'Bottom', 'Bowl', 'Bowling', 'Box', 'Boxer', 'Bracelet', 'Brain', 'Brake', 'Branch', 'Brand', 'Brandy', 'Brass', 'Bread', 'Break', 'Breakfast', 'Breast', 'Brick', 'Bridge', 'Briefcase', 'Broccoli', 'Brochure', 'Broom', 'Brush', 'Bubble', 'Bucket', 'Buckle', 'Budget', 'Buffer', 'Buffet', 'Bug', 'Building', 'Bulb', 'Bull', 'Bulldozer', 'Bullet', 'Bun', 'Bunk', 'Buoy', 'Burger', 'Bus', 'Bush', 'Business', 'Butcher', 'Butter', 'Butterfly', 'Button', 'Byte']
    },
    'C': {
        'NAME': ['Caleb', 'Cameron', 'Camilla', 'Candace', 'Candice', 'Carl', 'Carla', 'Carlos', 'Carly', 'Carmen', 'Carol', 'Caroline', 'Carolyn', 'Carrie', 'Casey', 'Cassandra', 'Catherine', 'Cathy', 'Cecilia', 'Cedric', 'Celina', 'Chad', 'Charles', 'Charlie', 'Charlotte', 'Chase', 'Chelsea', 'Cheryl', 'Chloe', 'Chris', 'Christian', 'Christina', 'Christine', 'Christopher', 'Cindy', 'Claire', 'Clara', 'Clarence', 'Claudia', 'Clayton', 'Clifford', 'Clint', 'Clyde', 'Codey', 'Cody', 'Cole', 'Colin', 'Colleen', 'Connor', 'Constance', 'Corey', 'Corinne', 'Courtney', 'Craig', 'Crystal', 'Curtis', 'Cynthia'],
        'VEGETABLE': ['Cabbage', 'Cactus', 'Calabash', 'Cannellini Beans', 'Capers', 'Carrot', 'Cassava', 'Cauliflower', 'Celery', 'Chard', 'Cherry Tomato', 'Chickpeas', 'Chicory', 'Chili Pepper', 'Chives', 'Collard Greens', 'Corn', 'Courgette', 'Cucumber'],
        'FRUIT': ['Cacao', 'Cactus Pear', 'Canary Melon', 'Cantaloupe', 'Cape Gooseberry', 'Carambola', 'Cardamom', 'Carob', 'Cashew Apple', 'Cassava', 'Cempedak', 'Cherry', 'Chico', 'Chili Pepper', 'China Pear', 'Chinese Quince', 'Citron', 'Clementine', 'Cloudberry', 'Coconut', 'Coffee Cherry', 'Cranberry', 'Cucumber', 'Currant', 'Custard Apple'],
        'CITY': ['Cairo', 'Calcutta', 'Calgary', 'Cali', 'Canberra', 'Cancun', 'Cannes', 'Cape Town', 'Caracas', 'Cardiff', 'Casablanca', 'Catania', 'Chengdu', 'Chennai', 'Chicago', 'Chongqing', 'Christchurch', 'Cincinnati', 'Cleveland', 'Cologne', 'Colombo', 'Columbus', 'Conakry', 'Copenhagen', 'Cordoba', 'Cork', 'Coventry', 'Curitiba', 'Cusco'],
        'JOB': ['Cabinetmaker', 'Cameraman', 'Captain', 'Cardiologist', 'Caregiver', 'Carpenter', 'Cartographer', 'Cartoonist', 'Cashier', 'Caterer', 'Cellist', 'Chauffeur', 'Chef', 'Chemist', 'Chief', 'Chiropractor', 'Choreographer', 'Civil Engineer', 'Cleaner', 'Clergy', 'Clerk', 'Coach', 'Cobbler', 'Coder', 'Columnist', 'Comedian', 'Composer', 'Concierge', 'Conductor', 'Consultant', 'Contractor', 'Cook', 'Cop', 'Copywriter', 'Coroner', 'Courier', 'Critic', 'Curator', 'Customer Service'],
        'ANIMAL': ['Camel', 'Canary', 'Capybara', 'Caribou', 'Carp', 'Cassowary', 'Cat', 'Caterpillar', 'Catfish', 'Centipede', 'Chameleon', 'Chamois', 'Cheetah', 'Chicken', 'Chihuahua', 'Chimpanzee', 'Chinchilla', 'Chipmunk', 'Cicada', 'Clam', 'Clownfish', 'Cobra', 'Cockatoo', 'Cockroach', 'Cod', 'Collie', 'Condor', 'Constrictor', 'Coral', 'Cougar', 'Cow', 'Coyote', 'Crab', 'Crane', 'Crawfish', 'Crayfish', 'Cricket', 'Crocodile', 'Crow', 'Cuckoo', 'Cuttlefish'],
        'INANIMATE': ['Cab', 'Cabinet', 'Cable', 'Cactus', 'Cage', 'Cake', 'Calculator', 'Calendar', 'Camera', 'Camp', 'Can', 'Canal', 'Candle', 'Candy', 'Cane', 'Cannon', 'Canoe', 'Canvas', 'Cap', 'Cape', 'Capital', 'Car', 'Card', 'Cardboard', 'Cardigan', 'Cargo', 'Carpet', 'Carriage', 'Carrot', 'Cart', 'Carton', 'Case', 'Cash', 'Cassette', 'Cast', 'Castle', 'Cat', 'Catalog', 'Cathedral', 'Cattle', 'Cave', 'CD', 'Ceiling', 'Celery', 'Cell', 'Cellar', 'Cello', 'Cement', 'Cemetery', 'Cent', 'Center', 'Ceramic', 'Cereal', 'Certificate', 'Chain', 'Chair', 'Chalk', 'Chamber', 'Champagne', 'Channel', 'Chapel', 'Character', 'Charcoal', 'Chart', 'Check', 'Checkbook', 'Cheese', 'Chef', 'Chemical', 'Cherry', 'Chess', 'Chest', 'Chicken', 'Child', 'Chimney', 'Chin', 'Chip', 'Chocolate', 'Choir', 'Church', 'Cigar', 'Cigarette', 'Cinema', 'Circle', 'Circuit', 'Circus', 'City', 'Clam', 'Clarinet', 'Class', 'Classic', 'Classroom', 'Claw', 'Clay', 'Cleaner', 'Click', 'Client', 'Cliff', 'Climate', 'Clinic', 'Clip', 'Clock', 'Close', 'Closet', 'Cloth', 'Clothes', 'Clothing', 'Cloud', 'Club', 'Clutch', 'Coach', 'Coal', 'Coast', 'Coat', 'Cobweb', 'Cockroach', 'Cocktail', 'Cocoa', 'Coconut', 'Coffee', 'Coin', 'Cold', 'Collar', 'Collection', 'College', 'Cologne', 'Color', 'Comb', 'Comic', 'Command', 'Comment', 'Commerce', 'Commission', 'Committee', 'Common', 'Company', 'Compass', 'Competition', 'Complaint', 'Computer', 'Concrete', 'Condition', 'Cone', 'Conference', 'Confetti', 'Connection', 'Console', 'Consonant', 'Contact', 'Container', 'Content', 'Contest', 'Context', 'Contract', 'Control', 'Conversation', 'Cook', 'Cooker', 'Cookie', 'Cooking', 'Cooler', 'Copper', 'Copy', 'Coral', 'Cord', 'Core', 'Cork', 'Corn', 'Corner', 'Correction', 'Corridor', 'Cost', 'Costume', 'Cottage', 'Cotton', 'Couch', 'Council', 'Counter', 'Country', 'County', 'Couple', 'Coupon', 'Course', 'Court', 'Cousin', 'Cover', 'Cow', 'Crab', 'Crack', 'Cracker', 'Craft', 'Crane', 'Crash', 'Crate', 'Crayon', 'Cream', 'Creation', 'Creative', 'Creature', 'Credit', 'Creek', 'Crew', 'Crib', 'Cricket', 'Criminal', 'Crisis', 'Critic', 'Cross', 'Crowd', 'Crown', 'Cruiser', 'Crust', 'Crystal', 'Cube', 'Cucumber', 'Cult', 'Cup', 'Cupboard', 'Curtain', 'Curve', 'Cushion', 'Custom', 'Customer', 'Cut', 'Cycle', 'Cylinder']
    },
    'D': {
        'NAME': ['Daisy', 'Dale', 'Damian', 'Damon', 'Dan', 'Dana', 'Daniel', 'Danielle', 'Danny', 'Daphne', 'Darlene', 'Darren', 'Darryl', 'Dave', 'David', 'Dawn', 'Dean', 'Deanna', 'Debbie', 'Deborah', 'Debra', 'Declan', 'Deirdre', 'Delia', 'Della', 'Delores', 'Denis', 'Dennis', 'Derek', 'Derrick', 'Desiree', 'Destiny', 'Devin', 'Diana', 'Diane', 'Dianne', 'Diego', 'Dillon', 'Dina', 'Dion', 'Dirk', 'Dominic', 'Don', 'Donald', 'Donna', 'Dora', 'Doreen', 'Doris', 'Dorothy', 'Doug', 'Douglas', 'Drew', 'Duane', 'Dustin', 'Dwayne', 'Dwight', 'Dylan'],
        'VEGETABLE': ['Daikon', 'Dandelion', 'Dasheen', 'Dill', 'Drumstick'],
        'FRUIT': ['Damson', 'Date', 'Date Plum', 'Davidson Plum', 'Dewberry', 'Dragonfruit', 'Durian'],
        'CITY': ['Da Nang', 'Dakar', 'Dallas', 'Damascus', 'Dar es Salaam', 'Darwin', 'Davao City', 'Dayton', 'Delhi', 'Denver', 'Des Moines', 'Detroit', 'Dhaka', 'Dijon', 'Djibouti', 'Doha', 'Donetsk', 'Dortmund', 'Douala', 'Dresden', 'Dubai', 'Dublin', 'Durban', 'Dushanbe', 'Dusseldorf'],
        'JOB': ['Dancer', 'Data Analyst', 'Data Scientist', 'Dealer', 'Dean', 'Deckhand', 'Decorator', 'Delivery Driver', 'Dentist', 'Designer', 'Detective', 'Developer', 'Dietitian', 'Diplomat', 'Director', 'Disk Jockey', 'Diver', 'Doctor', 'Dog Trainer', 'Doll Maker', 'Doorman', 'Draftsman', 'Driver', 'Drummer', 'Dry Cleaner', 'Dustman'],
        'ANIMAL': ['Dachshund', 'Dalmatian', 'Damselfly', 'Deer', 'Dhole', 'Dingo', 'Dinosaur', 'Doberman', 'Dodo', 'Dog', 'Dogfish', 'Dolphin', 'Donkey', 'Dormouse', 'Dove', 'Dragon', 'Dragonfly', 'Drake', 'Dromedary', 'Duck', 'Dugong', 'Dung Beetle', 'Dunkleosteus', 'Duiker'],
        'INANIMATE': ['Dagger', 'Daisy', 'Dam', 'Dance', 'Dandelion', 'Danger', 'Dart', 'Dashboard', 'Data', 'Database', 'Date', 'Daughter', 'Day', 'Dead', 'Deal', 'Dealer', 'Death', 'Debt', 'Deck', 'Decoration', 'Degree', 'Delay', 'Deli', 'Delivery', 'Demand', 'Democracy', 'Den', 'Denim', 'Dentist', 'Deodorant', 'Department', 'Departure', 'Deposit', 'Depth', 'Description', 'Design', 'Designer', 'Desk', 'Desktop', 'Dessert', 'Detail', 'Detective', 'Development', 'Device', 'Devil', 'Dew', 'Diadem', 'Diagram', 'Dial', 'Diamond', 'Diaper', 'Diary', 'Dice', 'Dictionary', 'Diet', 'Difference', 'Difficulty', 'Digestion', 'Digger', 'Digital', 'Dimension', 'Dime', 'Dinner', 'Dinosaur', 'Diploma', 'Direction', 'Dirt', 'Disadvantage', 'Disaster', 'Disc', 'Disco', 'Discount', 'Discovery', 'Discussion', 'Disease', 'Dish', 'Dishwasher', 'Disk', 'Display', 'Distance', 'Distribution', 'District', 'Ditch', 'Diver', 'Divider', 'Diving', 'Division', 'Dock', 'Doctor', 'Document', 'Dog', 'Doll', 'Dollar', 'Dolphin', 'Domain', 'Dome', 'Dominion', 'Donation', 'Donkey', 'Donut', 'Door', 'Doorbell', 'Doorknob', 'Doorway', 'Dot', 'Double', 'Dough', 'Doughnut', 'Down', 'Draft', 'Drag', 'Dragon', 'Dragonfly', 'Drain', 'Drama', 'Draw', 'Drawer', 'Drawing', 'Dream', 'Dress', 'Dresser', 'Dressing', 'Drill', 'Drink', 'Drive', 'Driver', 'Driveway', 'Drop', 'Drum', 'Drummer', 'Dryer', 'Duck', 'Duckling', 'Duct', 'Duffel', 'Dump', 'Dumpster', 'Dungeon', 'Duplex', 'Dust', 'Duster', 'Duty', 'DVD', 'Dwelling', 'Dynamite', 'Dynamo']
    },
    'E': {
        'NAME': ['Earl', 'Earnest', 'Ed', 'Eddie', 'Eden', 'Edgar', 'Edith', 'Edmond', 'Edmund', 'Edna', 'Edward', 'Edwin', 'Eileen', 'Elaine', 'Eleanor', 'Elena', 'Eli', 'Elias', 'Elijah', 'Elisa', 'Elisabeth', 'Elise', 'Eliza', 'Elizabeth', 'Ella', 'Ellen', 'Elliott', 'Ellis', 'Elmer', 'Eloise', 'Elsa', 'Elsie', 'Elton', 'Elvin', 'Elvis', 'Emily', 'Emma', 'Emmett', 'Eric', 'Erica', 'Erik', 'Erin', 'Ernest', 'Ernie', 'Erwin', 'Estelle', 'Esther', 'Ethan', 'Ethel', 'Eugene', 'Eula', 'Eunice', 'Eva', 'Evan', 'Evelyn', 'Everett', 'Ezra'],
        'VEGETABLE': ['Edamame', 'Eggplant', 'Endive', 'Escarole'],
        'FRUIT': ['Eggfruit', 'Elderberry', 'Elephant Apple', 'Emblica', 'Emu Berry', 'Entawak', 'Etrog', 'Evergreen Huckleberry'],
        'CITY': ['East London', 'Edinburgh', 'Edmonton', 'Eindhoven', 'El Paso', 'El Vandrell', 'Eldoret', 'Elgin', 'Elizabeth', 'Elk Grove', 'Elmina', 'Eneabba', 'Enschede', 'Enugu', 'Erbil', 'Erie', 'Esbjerg', 'Escondido', 'Espoo', 'Eugene', 'Evansville', 'Everett', 'Exeter'],
        'JOB': ['Ecologist', 'Economist', 'Editor', 'Educator', 'Electrician', 'Electronics Technician', 'Elementary School Teacher', 'Elevator Mechanic', 'Embalmer', 'Emergency Medical Technician', 'Engine Driver', 'Engineer', 'Engraver', 'Entertainer', 'Entomologist', 'Entrepreneur', 'Environmentalist', 'Epidemiologist', 'Equity Trader', 'Ergonomist', 'Estate Agent', 'Estimator', 'Ethicist', 'Event Planner', 'Examiner', 'Excavator', 'Executive', 'Executor', 'Exterminator', 'Extra'],
        'ANIMAL': ['Eagle', 'Earthworm', 'Earwig', 'Echidna', 'Eel', 'Egret', 'Eider', 'Eland', 'Elephant', 'Elephant Seal', 'Elk', 'Emu', 'Ermine'],
        'INANIMATE': ['Eagle', 'Ear', 'Earphone', 'Earring', 'Earth', 'Earthquake', 'Easel', 'East', 'Easter', 'Ebook', 'Eclipse', 'Edge', 'Editor', 'Education', 'Effect', 'Egg', 'Eggplant', 'Eggshell', 'Ego', 'Eight', 'Ejector', 'Elbow', 'Elderberry', 'Election', 'Electricity', 'Electron', 'Electronics', 'Element', 'Elephant', 'Elevator', 'Email', 'Emerald', 'Emery', 'Emission', 'Emotion', 'Empire', 'Employee', 'Employer', 'Encyclopedia', 'End', 'Enemy', 'Energy', 'Engine', 'Engineer', 'Engineering', 'Entertainment', 'Entrance', 'Entry', 'Envelope', 'Environment', 'Envy', 'Epoxy', 'Equal', 'Equinox', 'Equipment', 'Era', 'Eraser', 'Error', 'Escalator', 'Essay', 'Establishment', 'Estate', 'Estimate', 'Ethernet', 'Europe', 'Evening', 'Event', 'Evidence', 'Exam', 'Examination', 'Example', 'Exchange', 'Exclamation', 'Exercise', 'Exhibit', 'Exhibition', 'Exit', 'Expansion', 'Experience', 'Experiment', 'Expert', 'Explanation', 'Explosion', 'Export', 'Expression', 'Extension', 'Extent', 'External', 'Extinguisher', 'Eye', 'Eyebrow', 'Eyeglasses', 'Eyelash', 'Eyeliner', 'Eyes']
    },
    'F': {
        'NAME': ['Fabian', 'Faith', 'Fallon', 'Fannie', 'Faye', 'Felicia', 'Felicity', 'Felix', 'Fernando', 'Fern', 'Fiona', 'Fletcher', 'Flora', 'Florence', 'Floyd', 'Ford', 'Forest', 'Forrest', 'Foster', 'Fran', 'Frances', 'Francesca', 'Francine', 'Francis', 'Francisco', 'Frank', 'Frankie', 'Franklin', 'Fred', 'Freda', 'Freddie', 'Frederick', 'Fredrick', 'Freeman', 'Freida', 'Frieda', 'Fritz'],
        'VEGETABLE': ['Fava Bean', 'Fennel', 'Fiddlehead Fern', 'Field Pea', 'Flageolet Bean', 'French Bean', 'Frisee'],
        'FRUIT': ['Fairchild Tangerine', 'False Mastic', 'Feijoa', 'Fig', 'Finger Lime', 'Florida Strangler Fig', 'Forest Strawberries', 'Fox Grape', 'Fuji Apple'],
        'CITY': ['Faisalabad', 'Fargo', 'Faro', 'Fayetteville', 'Fes', 'Fez', 'Flagstaff', 'Flint', 'Florence', 'Florianopolis', 'Foggia', 'Fontana', 'Fort Collins', 'Fort Lauderdale', 'Fort Wayne', 'Fort Worth', 'Fortaleza', 'Frankfurt', 'Freetown', 'Fremont', 'Fresno', 'Fukuoka', 'Fukushima', 'Funafuti', 'Funchal'],
        'JOB': ['Fabricator', 'Facilitator', 'Factory Worker', 'Falconer', 'Farmer', 'Farmhand', 'Fashion Designer', 'Fence', 'File Clerk', 'Film Critic', 'Film Director', 'Film Editor', 'Filmmaker', 'Financial Analyst', 'Financial Planner', 'Firefighter', 'Fisherman', 'Fitness Instructor', 'Fitter', 'Flight Attendant', 'Flight Engineer', 'Floor Layer', 'Florist', 'Flutist', 'Food Critic', 'Food Scientist', 'Footballer', 'Foreman', 'Forensic Scientist', 'Forester', 'Forklift Driver', 'Foster Parent', 'Frame Maker', 'Fraud Investigator', 'Freelancer', 'Fundraiser', 'Funeral Director', 'Furniture Restorer', 'Furrier'],
        'ANIMAL': ['Falcon', 'Ferret', 'Finch', 'Firefly', 'Fish', 'Flamingo', 'Flea', 'Fly', 'Flying Fish', 'Flying Squirrel', 'Fossa', 'Fox', 'Frigatebird', 'Frog', 'Fruit Bat'],
        'INANIMATE': ['Fabric', 'Face', 'Facility', 'Fact', 'Factor', 'Factory', 'Fair', 'Fairy', 'Fall', 'Family', 'Fan', 'Fang', 'Farm', 'Farmer', 'Fat', 'Father', 'Faucet', 'Fear', 'Feast', 'Feather', 'Feature', 'February', 'Fee', 'Feed', 'Feedback', 'Feel', 'Feeling', 'Feet', 'Fence', 'Fender', 'Fern', 'Ferry', 'Festival', 'Fiber', 'Fiberglass', 'Fiction', 'Field', 'Fifth', 'Fight', 'Fighter', 'Figure', 'File', 'Filing', 'Fill', 'Filler', 'Film', 'Filter', 'Final', 'Finance', 'Finding', 'Fine', 'Finger', 'Fingerprint', 'Finish', 'Fire', 'Firearm', 'Firefighter', 'Fireman', 'Fireplace', 'Firewall', 'Firework', 'Firm', 'First', 'Fish', 'Fisherman', 'Fishing', 'Fist', 'Fit', 'Fitness', 'Five', 'Fix', 'Flag', 'Flame', 'Flamingo', 'Flannel', 'Flash', 'Flashlight', 'Flat', 'Flavor', 'Flax', 'Flesh', 'Flight', 'Flint', 'Float', 'Flock', 'Flood', 'Floor', 'Florist', 'Flour', 'Flow', 'Flower', 'Flu', 'Flute', 'Fly', 'Flyer', 'Foam', 'Fog', 'Foil', 'Folder', 'Font', 'Food', 'Foot', 'Football', 'Footnote', 'Force', 'Forehead', 'Forest', 'Fork', 'Form', 'Format', 'Fort', 'Fortnight', 'Fortress', 'Fortune', 'Forum', 'Foundation', 'Fountain', 'Four', 'Fowl', 'Fox', 'Frame', 'Framework', 'Franc', 'France', 'Fraud', 'Freckle', 'Freedom', 'Freezer', 'Freight', 'Frequency', 'Friday', 'Fridge', 'Friend', 'Frog', 'Front', 'Frost', 'Fruit', 'Fuel', 'Full', 'Fun', 'Function', 'Fund', 'Funeral', 'Fur', 'Furnace', 'Furniture', 'Fuse', 'Future']
    }
};
