export const db_G_L = {
    'G': {
        'NAME': ['Gabriel', 'Gabriella', 'Gabrielle', 'Gail', 'Gale', 'Garrett', 'Garry', 'Gary', 'Gavin', 'Gayle', 'Gene', 'Genevieve', 'Geoffrey', 'George', 'Georgia', 'Gerald', 'Geraldine', 'Gerard', 'Geri', 'German', 'Gerry', 'Gertrude', 'Gia', 'Gianna', 'Gina', 'Ginger', 'Gino', 'Giovanni', 'Giselle', 'Giuseppe', 'Gladys', 'Glen', 'Glenda', 'Glenn', 'Gloria', 'Glynis', 'Goldie', 'Gordon', 'Grace', 'Gracie', 'Graham', 'Grant', 'Greg', 'Gregg', 'Gregory', 'Greta', 'Gretchen', 'Griffin', 'Grover', 'Guadalupe', 'Guillermo', 'Gus', 'Gustavo', 'Guy', 'Gwen', 'Gwendolyn'],
        'VEGETABLE': ['Galangal', 'Garbanzo Bean', 'Garden Crest', 'Garlic', 'Garlic Chives', 'Ginger', 'Golden Beet', 'Gourd', 'Green Bean', 'Green Onion', 'Green Pepper', 'Guar'],
        'FRUIT': ['Gac Fruit', 'Galia Melon', 'Gamboge', 'Genip', 'Giant Granadilla', 'Goji Berry', 'Golden Apple', 'Gooseberry', 'Gorham Pear', 'Goumi', 'Governor’s Plum', 'Granadilla', 'Grape', 'Grapefruit', 'Green Apple', 'Greengage', 'Ground Cherry', 'Grumichama', 'Guava'],
        'CITY': ['Gaborone', 'Galway', 'Gary', 'Gdansk', 'Geneva', 'Genoa', 'Georgetown', 'Ghent', 'Gibraltar', 'Giza', 'Glasgow', 'Glendale', 'Gold Coast', 'Gothenburg', 'Granada', 'Grand Rapids', 'Graz', 'Green Bay', 'Greensboro', 'Grenoble', 'Guadalajara', 'Guangzhou', 'Guatemala City', 'Guayaquil', 'Guilin', 'Guiyang'],
        'JOB': ['Game Developer', 'Game Warden', 'Gardener', 'Gastroenterologist', 'Gem Cutter', 'General Practitioner', 'Geneticist', 'Geographer', 'Geologist', 'Geophysicist', 'Geriatrician', 'Ghostwriter', 'Glass Blower', 'Glazier', 'Goldsmith', 'Golfer', 'Governor', 'Graphic Designer', 'Greengrocer', 'Groundskeeper', 'Guide', 'Guitarist', 'Gunsmith', 'Gymnast', 'Gynecologist'],
        'ANIMAL': ['Galapagos Tortoise', 'Gazelle', 'Gecko', 'Gerbil', 'Gibbon', 'Giraffe', 'Gnat', 'Gnu', 'Goat', 'Goldfinch', 'Goldfish', 'Goose', 'Gopher', 'Gorilla', 'Goshawk', 'Grasshopper', 'Great Dane', 'Great White Shark', 'Grebe', 'Greyhound', 'Grizzly Bear', 'Groundhog', 'Grouse', 'Guinea Fowl', 'Guinea Pig', 'Gull', 'Guppy'],
        'INANIMATE': ['Gadget', 'Gage', 'Gallery', 'Galley', 'Gallon', 'Game', 'Garage', 'Garbage', 'Garden', 'Garlic', 'Garment', 'Gas', 'Gasoline', 'Gate', 'Gateway', 'Gauge', 'Gavel', 'Gazebo', 'Gear', 'Gearbox', 'Gel', 'Gem', 'General', 'Generator', 'Genie', 'Genius', 'Genre', 'Geography', 'Ghost', 'Giant', 'Gift', 'Gig', 'Ginger', 'Giraffe', 'Girl', 'Glacier', 'Glance', 'Glass', 'Glasses', 'Globe', 'Glove', 'Glue', 'Goal', 'Goat', 'Gold', 'Goldfish', 'Golf', 'Gong', 'Good-bye', 'Goose', 'Gorge', 'Grade', 'Grain', 'Gram', 'Grammar', 'Grand', 'Grandfather', 'Grandmother', 'Grape', 'Graphic', 'Grass', 'Grasshopper', 'Grate', 'Grave', 'Gravy', 'Gray', 'Grease', 'Great-grandfather', 'Great-grandmother', 'Green', 'Greenhouse', 'Grenade', 'Grey', 'Grid', 'Grief', 'Grill', 'Grip', 'Grit', 'Grocery', 'Ground', 'Group', 'Growth', 'Guarantee', 'Guard', 'Guava', 'Guess', 'Guest', 'Guide', 'Guild', 'Guillotine', 'Guilt', 'Guitar', 'Gum', 'Gun', 'Gym', 'Gymnast', 'Gymnastics', 'Gyro']
    },
    'H': {
        'NAME': ['Hailey', 'Hal', 'Haley', 'Hallie', 'Hamilton', 'Hannah', 'Hans', 'Harley', 'Harold', 'Harriet', 'Harrison', 'Harry', 'Harvey', 'Hattie', 'Hayden', 'Hayley', 'Hazel', 'Heath', 'Heather', 'Hector', 'Heidi', 'Helen', 'Helena', 'Henrietta', 'Henry', 'Herbert', 'Herman', 'Heriberto', 'Hilary', 'Hilda', 'Hillary', 'Hollie', 'Holly', 'Homer', 'Hope', 'Horace', 'Howard', 'Hugh', 'Hugo', 'Humberto', 'Hunter'],
        'VEGETABLE': ['Habas Bean', 'Habanero', 'Hamburg Parsley', 'Haricot Bean', 'Horseradish', 'Hot Pepper', 'Hubbard Squash'],
        'FRUIT': ['Hackberry', 'Hadaden Pear', 'Hala Fruit', 'Hardy Kiwi', 'Hawthorn', 'Hhog Plum', 'Highbush Cranberry', 'Himalayan Mulberry', 'Honeydew', 'Horned Melon', 'Huckleberry', 'Huito'],
        'CITY': ['Haifa', 'Haiphong', 'Hakodate', 'Halifax', 'Hamburg', 'Hamhung', 'Hamilton', 'Hammamet', 'Hangzhou', 'Hanoi', 'Harare', 'Harbin', 'Hartford', 'Havana', 'Helsinki', 'Hermosillo', 'Hialeah', 'Hiroshima', 'Ho Chi Minh City', 'Hobart', 'Hong Kong', 'Honolulu', 'Houston', 'Hualien', 'Hue', 'Huntsville', 'Hyderabad'],
        'JOB': ['Haberdasher', 'Hairdresser', 'Handyman', 'Harbor Master', 'Hardware Engineer', 'Harpist', 'Hatter', 'Headhunter', 'Health Inspector', 'Heating Engineer', 'Helicopter Pilot', 'Herbalist', 'Historian', 'Homeopath', 'Horse Trainer', 'Horticulturist', 'Hotel Manager', 'Housekeeper', 'Human Resources Manager', 'Hunter', 'Hydrologist', 'Hygienist', 'Hypnotist'],
        'ANIMAL': ['Haddock', 'Halibut', 'Hammerhead Shark', 'Hamster', 'Hare', 'Harrier', 'Hawk', 'Hedgehog', 'Heron', 'Herring', 'Hippopotamus', 'Hornet', 'Horse', 'Horseshoe Crab', 'Hound', 'Housefly', 'Howler Monkey', 'Hummingbird', 'Humpback Whale', 'Hyena', 'Hyrax'],
        'INANIMATE': ['Habit', 'Hack', 'Hail', 'Hair', 'Hairbrush', 'Haircut', 'Half', 'Hall', 'Hallway', 'Halo', 'Ham', 'Hamburger', 'Hammer', 'Hammock', 'Hamster', 'Hand', 'Handball', 'Handcuff', 'Handle', 'Handsaw', 'Hanger', 'Harbor', 'Hardboard', 'Hardcover', 'Hardhat', 'Hardware', 'Harmonica', 'Harmony', 'Harp', 'Hat', 'Hatchet', 'Hate', 'Hawk', 'Hay', 'Head', 'Headlight', 'Headline', 'Headphones', 'Health', 'Hearing', 'Heart', 'Heat', 'Heater', 'Heaven', 'Hedge', 'Height', 'Heirloom', 'Helicopter', 'Helium', 'Hell', 'Helmet', 'Help', 'Hemp', 'Hen', 'Herb', 'Herd', 'Hero', 'Heron', 'Herring', 'Hexagon', 'Hide', 'High', 'High-rise', 'Highway', 'Hill', 'Hip', 'Hippo', 'Hippopotamus', 'History', 'Hit', 'Hive', 'Hobbies', 'Hobbit', 'Hobby', 'Hockey', 'Hoe', 'Hog', 'Hold', 'Hole', 'Holiday', 'Home', 'Homework', 'Honey', 'Hood', 'Hook', 'Hope', 'Horn', 'Horror', 'Horse', 'Hose', 'Hospital', 'Host', 'Hostel', 'Hotel', 'Hour', 'Hourglass', 'House', 'Houseboat', 'Hovercraft', 'Hub', 'Hubcap', 'Hug', 'Hull', 'Human', 'Humor', 'Hump', 'Hunger', 'Hunt', 'Hurricane', 'Hurry', 'Hurt', 'Husband', 'Hut', 'Hyacinth', 'Hydrant', 'Hydrogen', 'Hyena', 'Hyphen']
    },
    'I': {
        'NAME': ['Ian', 'Ida', 'Ignacio', 'Ike', 'Ilene', 'Imogene', 'Ina', 'India', 'Ines', 'Ingrid', 'Iola', 'Iona', 'Ira', 'Irene', 'Iris', 'Irma', 'Irvin', 'Irving', 'Isaac', 'Isabel', 'Isabella', 'Isabelle', 'Isaiah', 'Isiah', 'Isidro', 'Ismael', 'Israel', 'Ivan', 'Ivory', 'Ivy'],
        'VEGETABLE': ['Ice Plant', 'Iceberg Lettuce', 'Indian Corn', 'Indian Mustard', 'Indian Pea', 'Irish Moss', 'Italian Pepper'],
        'FRUIT': ['Icaco', 'Ice Apple', 'Ice Cream Bean', 'Ilama', 'Illawarra Plum', 'Imbe', 'Indian Almond', 'Indian Fig', 'Indian Jujube', 'Indian Prune', 'Indian Strawberry', 'Inga'],
        'CITY': ['Ibadan', 'Ibiza', 'Incheon', 'Independence', 'Indianapolis', 'Indore', 'Ingolstadt', 'Innsbruck', 'Inverness', 'Ioannina', 'Iowa City', 'Ipoh', 'Ipswich', 'Iquique', 'Iquitos', 'Irbil', 'Irkutsk', 'Irvine', 'Islamabad', 'Isfahan', 'Istanbul', 'Izmir', 'Izmit'],
        'JOB': ['Illustrator', 'Image Consultant', 'Immigration Officer', 'Immunologist', 'Importer', 'Industrial Designer', 'Information Officer', 'Information Systems Manager', 'Inspector', 'Instructor', 'Insulation Worker', 'Insurance Agent', 'Insurance Broker', 'Intelligence Officer', 'Interior Decorator', 'Interior Designer', 'Interpreter', 'Interviewer', 'Inventor', 'Investigator', 'Investment Banker', 'Ironworker', 'IT Consultant'],
        'ANIMAL': ['Ibis', 'Iguana', 'Impala', 'Indian Elephant', 'Indian Rhinoceros', 'Indri', 'Insect', 'Irish Setter', 'Irish Wolfhound', 'Ivory-billed Woodpecker'],
        'INANIMATE': ['Ice', 'Iceberg', 'Icebreaker', 'Icecream', 'Icicle', 'Idea', 'Identity', 'Igloo', 'Ignorance', 'Image', 'Imagination', 'Impact', 'Implement', 'Import', 'Importance', 'Impression', 'Improvement', 'Impulse', 'Inch', 'Incident', 'Income', 'Increase', 'Index', 'India', 'Industry', 'Infant', 'Infection', 'Inflation', 'Influence', 'Information', 'Ingot', 'Initial', 'Initiative', 'Injection', 'Injury', 'Ink', 'Inquiry', 'Insect', 'Inside', 'Insight', 'Inspection', 'Inspector', 'Instance', 'Instant', 'Instruction', 'Instrument', 'Insurance', 'Intention', 'Interaction', 'Interest', 'Interior', 'Internal', 'Internet', 'Interview', 'Introduction', 'Invention', 'Inventory', 'Investigation', 'Investment', 'Invitation', 'Invoice', 'Iron', 'Island', 'Issue', 'Item', 'Ivory', 'Ivy']
    },
    'J': {
        'NAME': ['Jack', 'Jackie', 'Jackson', 'Jacob', 'Jacqueline', 'Jacquelyn', 'Jade', 'Jaime', 'Jake', 'James', 'Jami', 'Jamie', 'Jan', 'Jana', 'Jane', 'Janet', 'Janice', 'Janie', 'Janis', 'Jared', 'Jarrod', 'Jarvis', 'Jasmine', 'Jason', 'Jasper', 'Javier', 'Jay', 'Jayden', 'Jean', 'Jeanette', 'Jeanne', 'Jeannette', 'Jeannie', 'Jeff', 'Jefferson', 'Jeffery', 'Jeffrey', 'Jenna', 'Jennie', 'Jennifer', 'Jenny', 'Jeremiah', 'Jeremy', 'Jermaine', 'Jerome', 'Jerry', 'Jess', 'Jesse', 'Jessica', 'Jessie', 'Jesus', 'Jewel', 'Jill', 'Jillian', 'Jim', 'Jimmie', 'Jimmy', 'Jo', 'Joan', 'Joann', 'Joanna', 'Joanne', 'Jocelyn', 'Jodi', 'Jodie', 'Jody', 'Joe', 'Joel', 'Joey', 'John', 'Johnathan', 'Johnnie', 'Johnny', 'Jon', 'Jonah', 'Jonathan', 'Jonathon', 'Jordan', 'Jorge', 'Jose', 'Josefina', 'Joseph', 'Josephine', 'Josh', 'Joshua', 'Josie', 'Joy', 'Joyce', 'Juan', 'Juana', 'Juanita', 'Judith', 'Judy', 'Julia', 'Julian', 'Juliana', 'Julianne', 'Julie', 'Juliet', 'Julio', 'Julius', 'June', 'Junior', 'Justin', 'Justine'],
        'VEGETABLE': ['Jack Bean', 'Jicama', 'Jerusalem Artichoke', 'Jalapeno', 'Japanese Eggplant', 'Japanese Radish'],
        'FRUIT': ['Jabuticaba', 'Jackfruit', 'Jambul', 'Japanese Plum', 'Jatoba', 'Java Apple', 'Jazz Apple', 'Jeruk', 'Jocote', 'Jonathan Apple', 'Jostaberry', 'Jujube', 'June Plum', 'Junglesop', 'Juniper Berry'],
        'CITY': ['Jackson', 'Jacksonville', 'Jaipur', 'Jakarta', 'Jalalabad', 'Jalandhar', 'Jamestown', 'Jammu', 'Jeddah', 'Jefferson City', 'Jeju', 'Jena', 'Jerez', 'Jersey City', 'Jerusalem', 'Johannesburg', 'Johnstown', 'Johor Bahru', 'Joliet', 'Jonesboro', 'Joplin', 'Juba', 'Jubail', 'Juneau', 'Jyvaskyla'],
        'JOB': ['Janitor', 'Jeweler', 'Jockey', 'Joiner', 'Journalist', 'Judge', 'Judoka', 'Juggler', 'Junior Doctor', 'Justice of the Peace'],
        'ANIMAL': ['Jabiru', 'Jacana', 'Jackal', 'Jackrabbit', 'Jaguar', 'Jaguarundi', 'Japanese Beetle', 'Jay', 'Jellyfish', 'Jerboa', 'John Dory', 'Junco', 'Jungle Fowl'],
        'INANIMATE': ['Jack', 'Jacket', 'Jackhammer', 'Jade', 'Jail', 'Jam', 'Jar', 'Jargon', 'Jaw', 'Jay', 'Jazz', 'Jealousy', 'Jeans', 'Jeep', 'Jelly', 'Jellyfish', 'Jet', 'Jewel', 'Jewelry', 'Jigsaw', 'Job', 'Jockey', 'Jogging', 'Joke', 'Journal', 'Journey', 'Joy', 'Judge', 'Judgement', 'Judo', 'Jug', 'Juice', 'Julienne', 'July', 'Jump', 'Jumper', 'June', 'Jungle', 'Junior', 'Junk', 'Jupiter', 'Jury', 'Justice', 'Jute']
    },
    'K': {
        'NAME': ['Kacey', 'Kaitlyn', 'Kara', 'Karen', 'Kari', 'Karin', 'Karina', 'Karl', 'Karla', 'Karyn', 'Kasey', 'Kate', 'Katelyn', 'Katherine', 'Kathleen', 'Kathrine', 'Kathryn', 'Kathy', 'Katie', 'Katrina', 'Katy', 'Kay', 'Kayla', 'Keira', 'Keith', 'Kelley', 'Kelli', 'Kellie', 'Kelly', 'Kelsey', 'Kelvin', 'Ken', 'Kendall', 'Kendra', 'Kendrick', 'Kenneth', 'Kenny', 'Kent', 'Kerry', 'Kevin', 'Kiara', 'Kim', 'Kimberly', 'Kirk', 'Kirsten', 'Krista', 'Kristen', 'Kristi', 'Kristie', 'Kristin', 'Kristina', 'Kristine', 'Kristy', 'Krystal', 'Kurt', 'Kyle'],
        'VEGETABLE': ['Kale', 'Kai-lan', 'Kelp', 'Kidney Bean', 'Kohlrabi', 'Komatsuna', 'Kombu', 'Kurrat'],
        'FRUIT': ['Kaffir Lime', 'Kahikatea', 'Kakadu Plum', 'Kaki', 'Kandis', 'Kangaroo Apple', 'Kapok', 'Karkalia', 'Karonda', 'Kei Apple', 'Kepel Fruit', 'Keule', 'Key Lime', 'Kiwano', 'Kiwi', 'Kiwifruit', 'Knobby Russet Apple', 'Korlan', 'Kumquat', 'Kutjera'],
        'CITY': ['Kabul', 'Kaduna', 'Kagoshima', 'Kairouan', 'Kaiserslautern', 'Kampala', 'Kandahar', 'Kano', 'Kansas City', 'Kaohsiung', 'Karachi', 'Karbala', 'Karlsruhe', 'Kathmandu', 'Kawasaki', 'Kazan', 'Kermo', 'Kharkiv', 'Khartoum', 'Khulna', 'Kiel', 'Kigali', 'Kingston', 'Kingstown', 'Kinshasa', 'Kirkuk', 'Kisangani', 'Kitchener', 'Kobe', 'Kochi', 'Kolkata', 'Krasnodar', 'Krasnoyarsk', 'Kuala Lumpur', 'Kumamoto', 'Kumasi', 'Kunming', 'Kuwait City', 'Kyoto'],
        'JOB': ['Karate Teacher', 'Kennel Worker', 'Key Grip', 'Keyboard Player', 'Kindergarten Teacher', 'Kinesiologist', 'Kitchen Hand', 'Kitchen Manager', 'Kite Designer', 'Knitter'],
        'ANIMAL': ['Kakapo', 'Kangaroo', 'Kangaroo Rat', 'Katydid', 'Kea', 'Kestrel', 'Killer Whale', 'King Cobra', 'King Crab', 'Kingfisher', 'Kinglet', 'Kingsnake', 'Kinkajou', 'Kissing Bug', 'Kite', 'Kiwi', 'Koala', 'Koi', 'Komodo Dragon', 'Kookaburra', 'Kouprey', 'Krill', 'Kudu'],
        'INANIMATE': ['Kaleidoscope', 'Kangaroo', 'Karate', 'Kayak', 'Kazoo', 'Kebab', 'Keep', 'Keg', 'Kelp', 'Kennel', 'Kerosene', 'Ketchup', 'Kettle', 'Kettledrum', 'Key', 'Keyboard', 'Keyhole', 'Khaki', 'Kick', 'Kid', 'Kidney', 'Kilogram', 'Kilometer', 'Kilt', 'Kimono', 'Kind', 'Kindergarten', 'King', 'Kingdom', 'Kiosk', 'Kiss', 'Kit', 'Kitchen', 'Kite', 'Kitten', 'Kiwi', 'Knee', 'Knickers', 'Knife', 'Knight', 'Knit', 'Knob', 'Knock', 'Knot', 'Knowledge', 'Knuckle', 'Koala', 'Kohlrabi', 'Kumquat', 'Kung fu']
    },
    'L': {
        'NAME': ['Lacey', 'Lacy', 'Ladonna', 'Lakeisha', 'Lana', 'Lance', 'Landon', 'Lane', 'Larry', 'Latasha', 'Latoya', 'Laura', 'Laurel', 'Lauren', 'Laurence', 'Laurie', 'Laverne', 'Lawrence', 'Leah', 'Leann', 'Leanna', 'Leanne', 'Lee', 'Leigh', 'Leila', 'Lela', 'Leland', 'Lena', 'Lenard', 'Lenny', 'Lenora', 'Leo', 'Leon', 'Leona', 'Leonard', 'Leonardo', 'Leonor', 'Leroy', 'Les', 'Lesa', 'Lesley', 'Leslie', 'Lester', 'Leticia', 'Levi', 'Lewis', 'Liam', 'Lila', 'Lillian', 'Lillie', 'Lilly', 'Lily', 'Lincoln', 'Linda', 'Lindsay', 'Lindsey', 'Linwood', 'Lionel', 'Lisa', 'Lisette', 'Lloyd', 'Logan', 'Lois', 'Lola', 'Lonnie', 'Lora', 'Loraine', 'Loren', 'Lorena', 'Lorene', 'Loretta', 'Lori', 'Lorraine', 'Lou', 'Louie', 'Louis', 'Louise', 'Lourdes', 'Lowell', 'Lucas', 'Lucia', 'Lucille', 'Lucinda', 'Lucy', 'Luella', 'Luis', 'Luisa', 'Luke', 'Lula', 'Luther', 'Luz', 'Lydia', 'Lyle', 'Lynda', 'Lynette', 'Lynn', 'Lynne'],
        'VEGETABLE': ['Lacinato Kale', 'Land Cress', 'Leek', 'Legumes', 'Lemongrass', 'Lentils', 'Lettuce', 'Lima Bean', 'Lo Bok', 'Long Bean', 'Lotus Root', 'Luffa'],
        'FRUIT': ['Lady Apple', 'Lambkin Melon', 'Langra Mango', 'Langsat', 'Lantana', 'Lardizabala', 'Lemon', 'Lemon Aspen', 'Leucaena', 'Lime', 'Limeberry', 'Limequat', 'Lingonberry', 'Loganberry', 'Longan', 'Loquat', 'Lucuma', 'Lulo', 'Lychee'],
        'CITY': ['La Paz', 'Lagos', 'Lahore', 'Lake Charles', 'Lancaster', 'Lansing', 'Laredo', 'Las Cruces', 'Las Palmas', 'Las Vegas', 'Lausanne', 'Leeds', 'Leicester', 'Leipzig', 'Leon', 'Lexington', 'Libreville', 'Liege', 'Lille', 'Lima', 'Limassol', 'Limerick', 'Lincoln', 'Lisbon', 'Little Rock', 'Liverpool', 'Ljubljana', 'Lodz', 'Lome', 'London', 'Londonderry', 'Long Beach', 'Los Angeles', 'Louisville', 'Luanda', 'Lubbock', 'Lucknow', 'Lusaka', 'Luxembourg', 'Lyon'],
        'JOB': ['Lab Technician', 'Laborer', 'Land Agent', 'Land Surveyor', 'Landscape Architect', 'Landscaper', 'Language Teacher', 'Lathe Operator', 'Launderer', 'Lawyer', 'Lecturer', 'Legal Secretary', 'Legislator', 'Lens Grinder', 'Librarian', 'Lifeguard', 'Lift Attendant', 'Light Technician', 'Lighting Designer', 'Line Worker', 'Linguist', 'Literary Agent', 'Lithographer', 'Litigation Executive', 'Loan Officer', 'Lobbyist', 'Lock Keeper', 'Locksmith', 'Locomotive Engineer', 'Logistics Manager', 'Loss Adjuster', 'Lumberjack'],
        'ANIMAL': ['Ladybug', 'Lamprey', 'Land Snail', 'Langur', 'Lark', 'Leech', 'Lemming', 'Lemur', 'Leopard', 'Leopard Cat', 'Leopard Seal', 'Leopard Tortoise', 'Liger', 'Limpet', 'Lion', 'Lionfish', 'Lizard', 'Llama', 'Lobster', 'Locust', 'Long-Eared Owl', 'Loon', 'Lorikeet', 'Loris', 'Louse', 'Lynx', 'Lyrebird'],
        'INANIMATE': ['Label', 'Laborer', 'Lace', 'Ladder', 'Ladle', 'Lady', 'Ladybug', 'Lagoon', 'Lake', 'Lamb', 'Lamp', 'Lampshade', 'Lance', 'Land', 'Landlord', 'Language', 'Lantern', 'Lap', 'Lapel', 'Laptop', 'Lard', 'Lark', 'Laser', 'Lash', 'Lathe', 'Latitude', 'Laugh', 'Laundry', 'Lava', 'Law', 'Lawn', 'Lawnmower', 'Lawyer', 'Layer', 'Lead', 'Leader', 'Leaf', 'League', 'Leak', 'Leather', 'Lecture', 'Leek', 'Leg', 'Legend', 'Legging', 'Legislation', 'Lemon', 'Lemonade', 'Lemur', 'Length', 'Lens', 'Lentil', 'Leopard', 'Lesson', 'Letter', 'Lettuce', 'Level', 'Lever', 'Liar', 'Liberty', 'Library', 'License', 'Licorice', 'Lid', 'Lie', 'Lieutenant', 'Life', 'Lifeboat', 'Lifeguard', 'Lift', 'Light', 'Lighthouse', 'Lighting', 'Lightning', 'Lilac', 'Lily', 'Limb', 'Lime', 'Limestone', 'Limit', 'Limousine', 'Line', 'Linen', 'Link', 'Lion', 'Lip', 'Lipstick', 'Liquid', 'Liquor', 'List', 'Literature', 'Litter', 'Liver', 'Lizard', 'Llama', 'Loaf', 'Loan', 'Lobster', 'Local', 'Location', 'Lock', 'Locket', 'Locomotive', 'Locust', 'Loft', 'Log', 'Logic', 'Logo', 'Lollipop', 'London', 'Look', 'Loop', 'Lord', 'Loss', 'Lotion', 'Lottery', 'Lounge', 'Love', 'Lover', 'Low', 'Luck', 'Luggage', 'Lumber', 'Lumberjack', 'Lunch', 'Lung', 'Lure', 'Lute', 'Luxury', 'Lychee', 'Lycra', 'Lynx', 'Lyric', 'Lyre']
    }
};
